// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Feed struct {
	ID                   uuid.UUID        `json:"id"`
	CreatedAt            pgtype.Timestamp `json:"created_at"`
	UpdatedAt            pgtype.Timestamp `json:"updated_at"`
	Name                 string           `json:"name"`
	Url                  string           `json:"url"`
	UserID               uuid.UUID        `json:"user_id"`
	LastFetchedAt        pgtype.Timestamp `json:"last_fetched_at"`
	FetchIntervalSeconds int32            `json:"fetch_interval_seconds"`
}

type FeedFollow struct {
	ID        uuid.UUID        `json:"id"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
	UserID    uuid.UUID        `json:"user_id"`
	FeedID    uuid.UUID        `json:"feed_id"`
}

type Post struct {
	ID          uuid.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Title       string           `json:"title"`
	Url         string           `json:"url"`
	Description *string          `json:"description"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	FeedID      uuid.UUID        `json:"feed_id"`
}

type PostRead struct {
	UserID uuid.UUID        `json:"user_id"`
	PostID uuid.UUID        `json:"post_id"`
	ReadAt pgtype.Timestamp `json:"read_at"`
}

type User struct {
	ID             uuid.UUID        `json:"id"`
	CreatedAt      pgtype.Timestamp `json:"created_at"`
	UpdatedAt      pgtype.Timestamp `json:"updated_at"`
	Username       string           `json:"username"`
	Email          string           `json:"email"`
	HashedPassword string           `json:"hashed_password"`
}
