// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package database

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPost = `-- name: CreatePost :execrows
INSERT INTO posts (title, link, description, published_at, feed_id)
    VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (link)
    DO NOTHING
`

type CreatePostParams struct {
	Title       string           `json:"title"`
	Link        string           `json:"link"`
	Description *string          `json:"description"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	FeedID      uuid.UUID        `json:"feed_id"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (int64, error) {
	result, err := q.db.Exec(ctx, createPost,
		arg.Title,
		arg.Link,
		arg.Description,
		arg.PublishedAt,
		arg.FeedID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPostsForUser = `-- name: GetPostsForUser :many
SELECT
    posts.id, posts.created_at, posts.updated_at, posts.title, posts.link, posts.description, posts.published_at, posts.feed_id,
    feeds.title AS feed_title,
    (post_reads.read_at IS NOT NULL)::boolean AS read
FROM
    posts
    JOIN feed_follows ON feed_follows.feed_id = posts.feed_id
    JOIN feeds ON feeds.id = posts.feed_id
    LEFT JOIN post_reads ON post_reads.post_id = posts.id
        AND post_reads.user_id = $1
WHERE
    feed_follows.user_id = $1
ORDER BY
    posts.published_at DESC NULLS LAST
LIMIT $2
`

type GetPostsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type GetPostsForUserRow struct {
	ID          uuid.UUID        `json:"id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	UpdatedAt   pgtype.Timestamp `json:"updated_at"`
	Title       string           `json:"title"`
	Link        string           `json:"link"`
	Description *string          `json:"description"`
	PublishedAt pgtype.Timestamp `json:"published_at"`
	FeedID      uuid.UUID        `json:"feed_id"`
	FeedTitle   string           `json:"feed_title"`
	Read        bool             `json:"read"`
}

func (q *Queries) GetPostsForUser(ctx context.Context, arg GetPostsForUserParams) ([]GetPostsForUserRow, error) {
	rows, err := q.db.Query(ctx, getPostsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPostsForUserRow
	for rows.Next() {
		var i GetPostsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Link,
			&i.Description,
			&i.PublishedAt,
			&i.FeedID,
			&i.FeedTitle,
			&i.Read,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPostRead = `-- name: MarkPostRead :exec
INSERT INTO post_reads (user_id, post_id)
    VALUES ($1, $2)
ON CONFLICT (user_id, post_id)
    DO NOTHING
`

type MarkPostReadParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) MarkPostRead(ctx context.Context, arg MarkPostReadParams) error {
	_, err := q.db.Exec(ctx, markPostRead, arg.UserID, arg.PostID)
	return err
}

const markPostUnread = `-- name: MarkPostUnread :exec
DELETE FROM post_reads
WHERE user_id = $1
    AND post_id = $2
`

type MarkPostUnreadParams struct {
	UserID uuid.UUID `json:"user_id"`
	PostID uuid.UUID `json:"post_id"`
}

func (q *Queries) MarkPostUnread(ctx context.Context, arg MarkPostUnreadParams) error {
	_, err := q.db.Exec(ctx, markPostUnread, arg.UserID, arg.PostID)
	return err
}
